# Generated by Django 3.1.5 on 2021-01-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
