# Generated by Django 3.1.5 on 2021-01-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_book_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
