# Generated by Django 3.1.5 on 2021-02-13 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_cart_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='Category',
        ),
    ]
