# Generated by Django 3.1.5 on 2021-02-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_cart_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
