# Generated by Django 3.1.5 on 2021-02-16 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_cart_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
    ]
