# Generated by Django 3.1.5 on 2021-02-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20210227_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='stars',
            field=models.IntegerField(default=3),
        ),
    ]
