# Generated by Django 3.1.5 on 2021-03-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_book_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='quantity',
            new_name='available_quantity',
        ),
        migrations.AddField(
            model_name='book',
            name='total_Stock',
            field=models.IntegerField(default=5),
        ),
    ]
